
GET http://localhost:3000/api/status?test=abcd HTTP/1.1

###
GET http://localhost:3000/api/items HTTP/1.1

### Create Item
POST http://localhost:3000/api/items HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Y2YzMmE1N2Y2NThlMzM5YmNmMjljYjQiLCJlbWFpbCI6InBjanBjajJAZ21haWwuY29tIiwiaWF0IjoxNTU5NDQyOTcyfQ.72xEu9gpQ1bqqprxhNakYOUqdt0dwgNv9B-Y3ce4F9I

{
  "title": "Hello World"
}

### Get One Item
GET http://localhost:3000/api/items/5cf27efd6320ac40c4f22daf HTTP/1.1

### Patch One Item
PATCH http://localhost:3000/api/items/5cf27efd6320ac40c4f22daf HTTP/1.1
Content-Type: application/json

{
  "title": "Hello Worl3343"
}

### Delete One Item
DELETE http://localhost:3000/api/items/5cf27f7c4060be08788cfd63 HTTP/1.1


## AUTH

### Sign Up
POST http://localhost:3000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
  "email": "pcjpcj2@gmail.com",
  "password": "1q2w3e4r"
}

### Sign In
POST http://localhost:3000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
  "email": "pcjpcj2@gmail.com",
  "password": "1q2w3e4r"
}

### Get All users
GET http://localhost:3000/api/users HTTP/1.1


### Get All users lists
GET http://localhost:3000/api/lists HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Y2Y1Mzg5NTk2MTY0MzIyZjhhOTAwMzgiLCJlbWFpbCI6InBjanBjajJAZ21haWwuY29tIiwiaWF0IjoxNTU5ODAzNDkxfQ.rAUFpqDV_XJqzRDM1uJQdbJavAHNBq3ejp_ozTmm6jk
Content-Type: application/json

### Create One List
POST http://localhost:3000/api/lists HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Y2Y1Mzg5NTk2MTY0MzIyZjhhOTAwMzgiLCJlbWFpbCI6InBjanBjajJAZ21haWwuY29tIiwiaWF0IjoxNTU5ODAzNDkxfQ.rAUFpqDV_XJqzRDM1uJQdbJavAHNBq3ejp_ozTmm6jk
Content-Type: application/json

{
  "title": "HELLO WORLD"
}
